### PR TITLE
Update maven-archetypes.md

### PR DESCRIPTION
**Pull request by cyrilde**
A missing step in the "Usage in IntelliJ IDEA" section has been added.

### CODE REVIEW

**Comment by koevskinikola** [comment]
Hi @cyrilde,

Thank you for your contribution. However, I can't find the options you are listing. What version of IntelliJ are you using? (I'm on 2021.1)

Best,
Nikola

**Comment by cyrilde** [comment]
> Hi @cyrilde,
> 
> Thank you for your contribution. However, I can't find the options you are listing. What version of IntelliJ are you using? (I'm on 2021.1)
> 
> Best,
> Nikola

Hey Nikola, 

have a look on the following screenshots (i've made them in 2021.1.3)

Screenshot 2021-07-09 at 09 37 06

Screenshot 2021-07-09 at 09 37 25

**Review by koevskinikola — APPROVED** [review]
Hi @cyrilde,

Sorry for the mixup. I reinstalled my IntelliJ and forgot to add the Maven Archetypes Plugin. After adding it, I can see the window. The new steps you added make sense now. I'll merge the changes asap.

Best,
Nikola

**Comment by koevskinikola** [comment]
I also added some typo fixes and backported this contribution to the 7.15 branch with 3e26beff.

Cheers,
Nikola

**Pull request closed without merging**
