### PR TITLE
Fix instruction for maven archetype in interactive mode

### PR DESCRIPTION
**Pull request by murdos**
archetypeCatalog is not supported anymore

### CODE REVIEW

**Comment by tmetzke** [comment]
Hi @murdos ,

thanks for your input on this!

May I ask how you came to the conclusion that `-DarchetypeCatalog` is not supported anymore?

From the [mojo documentation](https://maven.apache.org/archetype/maven-archetype-plugin/generate-mojo.html) I would conclude that the user property `archetypeCatalog` is supported. 
Furthermore, the [repository documentation](https://maven.apache.org/archetype/maven-archetype-plugin/archetype-repository.html) of the plugin states that `-DarchetypeRepository` is not supported anymore since plugin version 3.0.0.

Maybe you could clarify on this.

Best,
Tobias

**Comment by murdos** [comment]
Hi @tmetzke,

I confess I haven't read the mojo documentation. Since the other [section 'Full Automation'](https://github.com/camunda/camunda-docs-manual/blob/1c2b91360f890f3180c164ec97b57d5045a46ef1/content/user-guide/process-applications/maven-archetypes.md#full-automation) in the same document was using `-DarchetypeRepository` I thought the other section was just outdated.

Here 's what happened for me that has motivated the change:
```
$ mvn archetype:generate -Dfilter=org.camunda.bpm.archetype: -DarchetypeCatalog=https://app.camunda.com/nexus/content/repositories/camunda-bpm
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] >>> maven-archetype-plugin:3.0.1:generate (default-cli) > generate-sources @ standalone-pom >>>
[INFO]
[INFO] <<< maven-archetype-plugin:3.0.1:generate (default-cli) < generate-sources @ standalone-pom <<<
[INFO]
[INFO]
[INFO] --- maven-archetype-plugin:3.0.1:generate (default-cli) @ standalone-pom ---
[INFO] Generating project in Interactive mode
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.613 s
[INFO] Finished at: 2019-06-07T06:21:10+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.0.1:generate (default-cli) on project standalone-pom: archetypeCatalog 'https://app.camunda.com/nexus/content/repositories/camunda-bpm' is not supported anymore. Please read the plugin documentation for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```
So I've version `3.0.1` of `maven-archetype-plugin` installed locally, with Maven 3.6.1.

**Comment by murdos** [comment]
Also it seems that this changes has already been made in master: https://github.com/camunda/camunda-docs-manual/commit/8bbd0d29941caf5c90e18532562b1608ef0bf03d#diff-7d72492134d2ff5229d3554eb2cb288e

**Comment by tmetzke** [comment]
Hi @murdos,

thank you for the pointers!

So, I had a closer look at the [mojo documentation](https://maven.apache.org/archetype/maven-archetype-plugin/generate-mojo.html#archetypeCatalog). It states that you can use any of the three fixed values: `local`, `internal`, or `remote`. Those are helpful if you want to limit the number of archetypes to choose from in interactive mode.

Furthermore, if you want to specify the catalog to come from another repository (that you are not already using in your settings anyway), you have to adjust your `settings.xml` by adding the repository.

So, the gist of it:
* `-DarchetypeCatalog` is still supported, but only with values from a fixed list and not with a URL anymore
* using `-DarchetypeRepository` is not failing but unnecessary because the archetypes are available on Maven Central
* it looks like using `-DarchetypeRepository` has no effect anyway and is ignored by the plugin
* if you want to use a catalog from a repository that is not known in your setting, add it to the `settings.xml`

Would you like to change your PR and incorporate those findings?
You might as well open a new branch from master, start from there and file a new PR if you like.

Thanks again for spotting this and initiating this PR!

Best,
Tobias

**Comment by tasso94** [comment]
Hi,

we added the proposed fixed was added to the docs via #252.

Cheers,
Tassilo

**Pull request closed without merging**
