### PR TITLE
docs(update): handle Java 8 Time objects

### PR DESCRIPTION
**Pull request by tmetzke**
* documents added Jackson JSR-310 dependency to REST API & web apps

related to CAM-13937

### CODE REVIEW

**Review by koevskinikola — APPROVED** [review]

**Comment by tmetzke** [comment]
@christinaausley, can you please do a technical writing review? 🙂

**Comment by christinaausley** [comment]
From a technical writing perspective, this looks good to me. Well-worded and well-written, but may make sure sentences are either within one paragraph or have a space between paragraphs/sentences according to paragraph form. For example:

"Starting with version 2.12.0, Jackson [throws an exception](https://github.com/FasterXML/jackson-databind/issues/2683) in such cases. Therefore, the REST API and web applications now register an appropriate module.

This allows you to keep using Java 8 date and time data types when updating to a newer Jackson version. However, this can also lead to changed serialized data for such values."

**Comment by tmetzke** [comment]
Hi @christinaausley, thanks for the input.
If you have a look at https://stage.docs.camunda.org/manual/7.16/update/patch-level/#7-16-1-to-7-16-2-7-15-7-to-7-15-8, does it look as expected?

I guess this might be a misunderstanding in how Hugo picks up the markdown. Hugo strips away single newlines and considers all text as one paragraph. Only double newlines will create a new paragraph.

Let me know if I got anything wrong here 🙂

**Comment by christinaausley** [comment]
Excellent! Dismiss my spacing comments then. Thanks for clarifying as I'm still understanding the processing of Hugo.

One last note is that we do need to capitalize each word after its numerical introduction, followed by a period rather than a comma. For example:

1. **U**pdate the Process Engine library in your dependency management (Apache Maven, Gradle …)**.**
2. Re-package the application.
3. Deploy the new version of the application.

**Comment by tmetzke** [comment]
Thanks, Christina.
As I have not touched that part of the page with the bullet points, how should we handle this?
Should we create a new ticket and PR?

**Comment by christinaausley** [comment]
I'm happy to open up a PR and fix it -- will add you as a reviewer once it's good to go.

**Comment by tmetzke** [comment]
Sounds fantastic, thanks Christina 👍 🚀

**Pull request merged**
