### PR TITLE
chore(repo): rename Camunda BPM Platform to Camunda Platform

### PR DESCRIPTION
**Pull request by mboskamp**
Related to CAM-12950

### CODE REVIEW

**Review by marstamm — CHANGES_REQUESTED** [review]
This branch does not build

```
[en] REF_NOT_FOUND: Ref "/introduction/third-party-libraries/_index.md": ".../camunda-docs-manual/content/introduction/architecture.md:16:364": page not found
[en] REF_NOT_FOUND: Ref "/user-guide/license-use.md": ".../camunda-docs-manual/content/user-guide/camunda-bpm-run.md:73:54": page not found
[en] REF_NOT_FOUND: Ref "/introduction/third-party-libraries/_index.md": ".../camunda-docs-manual/content/reference/bpmn20/tasks/script-task.md:44:176": page not found
logged 3 error(s)
```

**Comment by mboskamp** [comment]
Sorry for that, should be okay now.

**Review by marstamm — CHANGES_REQUESTED** [review]
Works now :+1: 

I found one place where we still use Camunda BPM Run:
https://github.com/camunda/camunda-docs-manual/blob/3ecd99337edaa36d8b87cebfb7cf0de08575d5ff/content/user-guide/camunda-bpm-run.md#L74

Feel free to merge after adjusting this line

**Review by marstamm — APPROVED** [review]
Theme looks good :+1:

**Pull request merged**
