### PR TITLE
CAM-10775: Update manual.md

### PR DESCRIPTION
**Pull request by DavideStabelli**
I have documented a working fix for SPIN + NASHORN under WildFly.

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hello @DavideStabelli,

Thank for your interest in improving the documentation.
I would like to ask you more about the problem which you face since there might be another solution for it.

Could you please tell us more details about your setup:
* Camunda version
* Wildfly version
* What did you face as a problem? What did you try to achieve (a sample of your code)?
* How did you come up with the proposed solution? What else have you tried to perform in order to resolve the issue?

Best regards,
Yana

**Comment by DavideStabelli** [comment]
Hi @yanavasileva,
Thanks to you for the answare, and sorry for waiting 3 days but github didn't notify me your comment!

I'm actually useing Camunda 7.11 with wildfly 16 (basically i have unpacked the file downloaded from this link: https://camunda.com/download/).

My java version is the JDK 12.

I was just trying to use the spin library with a simple 

`S({"example":"example"})` 

and i got a 

```java
org.camunda.spin.Spin classNotFound exception
```

(i have to specify that it was an external JS script file)

After some test, i tried to deploy the same BPM on a tomcat server and it worked perfectly.

Then on your forum i found [this](https://forum.camunda.org/t/javascript-with-spin-results-in-classnotfoundexception-org-camunda-spin-spin-s/7096/11), and it worked perfectly also on wildfly.

**Comment by yanavasileva** [comment]
Hi @DavideStabelli,

Thank you for the provided information, I updated accordingly the created issue for this pull request:
https://app.camunda.com/jira/browse/CAM-10775
Also, I was able to reproduce the issue.
However, I am not certain that the suggested solution should be documented. I would rather prefer to investigate the issue and find the root cause of it to decide how to proceed further.

I'll leave the PR open for now and I'll come back later with my findings and/or decision on this.

Best regards,
Yana

**Comment by DavideStabelli** [comment]
Ok @yanavasileva! 
So i'll wait for your solution, in this way everything will be cleaner.

Thanks again,
Davide.

**Comment by yanavasileva** [comment]
Hi @DavideStabelli,

We will not merge the PR but rather continue the investigation on what is the root cause of the issue.
You can keep track of the Jira issue [CAM-10775](https://app.camunda.com/jira/browse/CAM-10775).
Thank you once again for your interest in improving our documentation.

Best regards,
Yana

**Pull request closed without merging**
