### PR TITLE
style(formatting): revise trial and enterprise links

### PR DESCRIPTION
**Pull request by christinaausley**
Related to https://jira.camunda.com/browse/CAMTEAM-278?filter=-2

### CODE REVIEW

**Comment by tasso94** [comment]
Hi @christinaausley,

I think the links need to be changed in this repository as well:
https://github.com/camunda/camunda-docs-theme/blob/master/layouts/shortcodes/enterprise.html

Best,
Tassilo

**Comment by christinaausley** [comment]
Nudging for review here @akeller as I'm sure it slipped through your inbox while you were out of the country 👍

**Comment by christinaausley** [comment]
> Hi @christinaausley,
> 
> I think the links need to be changed in this repository as well: https://github.com/camunda/camunda-docs-theme/blob/master/layouts/shortcodes/enterprise.html
> 
> Best, Tassilo

Adjusted in https://github.com/camunda/camunda-docs-theme/pull/34. Thanks!

**Review by akeller — APPROVED** [review]

**Comment by tasso94** [comment]
@christinaausley, in case this should be fixed for our maintenance versions (7.18, 7.17, 7.16) as well, we would need to raise dedicated PRs for these branches.

**Pull request merged**
