### PR TITLE
chore(update): finalize update guide to 7.20

### PR DESCRIPTION
**Pull request by tmetzke**
* Add JDK 8 discontinuation paragraph.
* Sort the sections by new features, environment updates, and discontinuations.

related to https://github.com/camunda/camunda-bpm-platform/issues/3335

### CODE REVIEW

**Comment by tmetzke** [comment]
**To reviewer**: Only JDK 8 section is new, the rest was just sorted accordingly.

**Comment by yanavasileva** [comment]
👍 Looks good and the new order makes more sense to me.

❓  I have comment on the WAS migration page. Should we make the title more explicit that covers WebSphere Liberty only? Something like:
```
title: "Update an IBM Websphere Liberty Installation from 7.19 to 7.20"

menu:
  main:
    name: "WebSphere Liberty"
```

🔧 I suggest to adjust row 39 on that page as well by removing `or update to 7.2`. Liberty users haven't updated to Camunda 7.2:
```
With your first Camunda installation, you have created a shared library named `Camunda`. We identify 
```

**Comment by tmetzke** [comment]
> ❓ I have comment on the WAS migration page. Should we make the title more explicit that covers WebSphere Liberty only? Something like:
> 
> ```
> title: "Update an IBM Websphere Liberty Installation from 7.19 to 7.20"
> 
> menu:
>   main:
>     name: "WebSphere Liberty"
> ```

I was asking myself the same thing, actually, but didn't follow through 😄 Looks like it's an idea that at least two people share now, I'll look into it 👍

> 🔧 I suggest to adjust row 39 on that page as well by removing `or update to 7.2`. Liberty users haven't updated to Camunda 7.2:
> 
> ```
> With your first Camunda installation, you have created a shared library named `Camunda`. We identify 
> ```

That makes a lot of sense, yes 👍

**Review by yanavasileva — APPROVED** [review]
👍

**Pull request merged**
