### PR TITLE
chore(process-engine): Add Decision Definitions for historyTimeToLive

### PR DESCRIPTION
**Pull request by psavidis**
relates to:  camunda/camunda-bpm-platform#2496

### CODE REVIEW

**Comment by psavidis** [comment]
Changing the Reviewer cause Miklas is sick.

**Comment by psavidis** [comment]
Changing the Reviewer cause Miklas is absent.

**Review by yanavasileva — APPROVED** [review]
👍 Small suggestion below.

**Comment by yanavasileva** [comment]
Memo: I didn't find any other places where `historyTimeToLive` is mentioned and needs adjustment. The History Cleanup page already claims the property is applied for DD.

**Pull request merged**
