### PR TITLE
(chore) docs: Update Capitalization of REST API

### PR DESCRIPTION
**Pull request by celanthe**
Updated capitalization of the words 'REST API'

### CODE REVIEW

**Review by akeller — COMMENTED** [review]
Thank you! 

Please confirm with @ThorbenLindhauer which branch this should get merged into since it's not tied to a release but is not super urgent to fix.

**Comment by ThorbenLindhauer** [comment]
Please make PRs to the `master` branch. It will then be released with the next minor release.

Cheers,
Thorben

**Comment by akeller** [comment]
@celanthe you should be able to edit this PR directly in the browser to be against the master branch. Let me know if you need any help.

**Comment by celanthe** [comment]
@akeller I changed the branch to `master` but I'm now getting merge conflicts. I'd love any help you can provide! Thank you so much! :)

**Comment by akeller** [comment]
Two methods, or three if you count me cleaning up this PR for you 😄 

1. Close this PR and repo and new one to make this change with the most recent master history.
2. Rebase this PR with the process below.
3. Ask me to rebase this PR, I'll follow the process below.


-----
I would recommend dropping the 15 commits from this PR that aren't yours. 

```
git clone https://github.com/camunda/camunda-docs-manual.git
cd camunda-docs-manual
git checkout celanthe-patch-1
git rebase -i HEAD~16
```

This will open VI or VIM in your terminal. It should already be in insert mode, if not hit "i". Where you see **pick** from the top 15 commits, you need to type **drop**. Make sure your last commit with the spelling changes is included. Save a quit with `:wq`.

`git push --force`

**Comment by celanthe** [comment]
Hi @akeller! :) I chose option two and have dropped the additional commits and picked the first initial commit. I hope this will work! :)

**Comment by akeller** [comment]
Excellent looks like this is a very simple merge. I'll go ahead and merge it now and let the team handle the release process.

**Pull request merged**
