### PR TITLE
CAM-13376: docs(layouts/index.html): Added Camunda Community Hub Information

### PR DESCRIPTION
**Pull request by celanthe**
- Added link to the Camunda Community Hub GitHub Organization
- Added additional contextual information about the Camunda Community Hub

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hello @celanthe, is this still a wip and a draft PR?
On side note, please have a look at our contribution guidelines for the commit message convention: https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md#commit-message-conventions

**Comment by celanthe** [comment]
/

> Hello @celanthe, is this still a wip and a draft PR?
> On side note, please have a look at our contribution guidelines for the commit message convention: https://github.com/camunda/camunda-bpm-platform/blob/master/CONTRIBUTING.md#commit-message-conventions

Hi Yana! I've gone ahead and made that change. This is ready for review. If you could assign Amara and Thorben as reviewers, that would be amazing. I don't have the permissions to do so myself! Thank you so much.

**Review by akeller — APPROVED** [review]
Looks good to me.

**Comment by akeller** [comment]
I just realized this was in the camunda-docs-manual repo, meaning this content lives with the versioned content. We'll need to make sure this persists across all new versions.

**Comment by yanavasileva** [comment]
I have created CAM-13376 to track the goal and progress of the contribution. Backporting to previous versions will be take care of Runtime team.

**Review by ThorbenLindhauer — CHANGES_REQUESTED** [review]
Hi @celanthe, this looks good to me. How about we remove the list of extension on this page (https://github.com/camunda/camunda-docs-manual/blob/5f614200b940e1d3549a8793be09d4e51f3d626b/layouts/index.html#L148-L206) since we now have the community hub? The list here in the documentation is not complete and it's hard for the dev team to keep up to date.

**Review by celanthe — COMMENTED** [review]
Made requested change to remove the list of extensions in this document.

**Review by ThorbenLindhauer — APPROVED** [review]

**Comment by ThorbenLindhauer** [comment]
Hey @celanthe,

thanks for your contribution, I merged it together with #920 via https://github.com/camunda/camunda-docs-manual/commit/d1f2fcf095acb2a06777ddbcc78cc50d37e2d44d. I'll now proceed with backporting until 7.12 and releasing the docs.

I ultimately decided to keep the current list of extensions. Most of the repositories in the list haven't been migrated to the hub yet and I think this list was a major point for people discovering the projects. Nevertheless, I would like to remove the lists from the core docs when migration has progressed further. We'll keep track of that with https://jira.camunda.com/browse/CAM-13375 and do it at latest at the end of Q3. Please let me know if disagree with this.

Cheers,
Thorben

**Pull request closed without merging**
