### PR TITLE
feat(archetypes): add Cockpit plugin archetype

### PR DESCRIPTION
**Pull request by falko**

### CODE REVIEW

**Comment by hawky-4s-** [comment]
Hi Falko, should I also backport it to 7.4 - 7.2 as there is also the cockpit archetype available?

**Comment by falko** [comment]
Yes, please.

**Comment by hawky-4s-** [comment]
Merged and cherry-picked to all branches down till 7.2

**Comment by falko** [comment]
THX!

Sent from mobile device
On Tue, Jul 12, 2016 at 1:53 PM, hawky-4s- <notifications@github.com<mailto:notifications@github.com>> wrote:


Merged and cherry-picked to all branches down till 7.2

-

**Pull request closed without merging**
