### PR TITLE
Change to the new artifactory domain

### PR DESCRIPTION
**Pull request by chaima-mnsr**
Related to INFRA-3183

### CODE REVIEW

**Review by Langleu — APPROVED** [review]
checked that the URL structure is correct but did not check that every single link is redirecting to something working but would assume everything is fine for the things that have been released already as only the domain changed.

**Comment by Langleu** [comment]
Don't forget to backport the change till 7.4 I think as 7.0-7.3 had a completely different structure.

**Review by ThorbenLindhauer — CHANGES_REQUESTED** [review]
Changes look good overall. Similar to https://github.com/camunda/camunda-docs-static/pull/257, there seem to be issues with links that point to the `internal` and `camunda-bpm-ee` groups. Let's try to resolve them first.

I will review the backports once we are finished with the master PR.

**Review by ThorbenLindhauer — APPROVED** [review]
As Chaima shared on slack, this is currently expected and will resolve once we communicate this to our users, so I will go ahead with merging.

**Pull request merged**
