### PR TITLE
CAM-11667

### PR DESCRIPTION
**Pull request by AndreyOsipkov**
[CAM-11667](https://app.camunda.com/jira/browse/CAM-11667)

### CODE REVIEW

**Comment by AndreyOsipkov** [comment]
signed

**Comment by tmetzke** [comment]
Hey @AndreyOsipkov,

thanks for providing those fixes!

It looks like you signed the CLA with your GitHub account, but the e-mail you used for the commit (osipkovas@mosreg.ru) is not connected to this account. Can you confirm that?
If that is the case, please either connect the e-mail to your account or change the commit's e-mail to one that is connected to your GitHub account already.

Best,
Tobias

**Comment by AndreyOsipkov** [comment]
I can not find where my mail is indicated osipkovas@mosreg.ru

**Comment by tmetzke** [comment]
The patch information shows the associated e-mail:
https://github.com/camunda/camunda-docs-manual/pull/484.patch

**Comment by AndreyOsipkov** [comment]
canceled the first commit, created a new one with correct mail

**Comment by tmetzke** [comment]
That complicated the branch tremendously unfortunately.
Could you squash the branch to one commit with the associated e-mail?
If you need help on this, you can consult our linked guide for example:
https://lefedt.de/blog/posts/2013/contributing-to-oss-through-pull-requests#cleanup-using-git-rebase

**Pull request closed without merging**
