### PR TITLE
CAM-12276: GPL Cooperation Commitment

### PR DESCRIPTION
**Pull request by mary-grace**
used [GPL Cooperation Commitment Company Template](https://github.com/gplcc/gplcc/blob/master/Company/GPL%20Cooperation%20Commitment-Company-Template.md) provided by RedHat

### CODE REVIEW

**Comment by mary-grace** [comment]
@ThorbenLindhauer @UlrikeLiss This is the standard commitment suggested by Red Hat in the GPL Cooperation Commitment. Let me know if you have any concerns or whether we can simply merge.

**Comment by UlrikeLiss** [comment]
The GPL Cooperation Commitment suggested by  Red Hat is ok for me. I assume we will adjust to our company name. Thx Uli

**Comment by mary-grace** [comment]
@UlrikeLiss yep - already done! Here are the actual changes: https://github.com/camunda/camunda-docs-manual/pull/655/commits/ef5450ad60d726a1d36da5a1d1065c71f10866d5

**Comment by ThorbenLindhauer** [comment]
CAM ticket: CAM-12276

**Comment by ThorbenLindhauer** [comment]
Thank you, I merged it to master with https://github.com/camunda/camunda-docs-manual/commit/084c0d3a8746484e980790fa9fba7d3080dbf352 and to the maintenance branches down to 7.11.

**Pull request closed without merging**
