### PR TITLE
chore(authorization): document system permissions and cleanup

### PR DESCRIPTION
**Pull request by mboskamp**
Related to CAM-14207

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
Looks good to me 👍

**Comment by mboskamp** [comment]
Hi @christinaausley, do you have time to check this documentation change? As discussed I tried to bold all permissions mentioned on this page.
Thanks :)

**Review by christinaausley — APPROVED** [review]
Minor adjustments made in latest commit. LGTM.

**Comment by mboskamp** [comment]
Awesome, thank you! :)

**Pull request merged**
