### PR TITLE
CAM-10753: fix typos in patch-level update guide

### PR DESCRIPTION
**Pull request by kgeis**
fix some typos and syntax

### CODE REVIEW

**Comment by kgeis** [comment]
I trust that you can find a way to accept this contribution without my lawyers getting involved.

**Comment by tmetzke** [comment]
Hi @kgeis,

thanks a lot for contributing this!

Unfortunately, the signed CLA legally is a new mandatory step in order to accept contributions, however small or big they are.
You only have to sign this once for this and all future contributions.
I hope that is acceptable for you.
Otherwise, I have to decline the contribution and we will then have to look into this ourselves.

Best,
Tobias

**Comment by tmetzke** [comment]
Hi @kgeis,

Due to the missing CLA I will close this PR and we will look into the issue ourselves.
Thanks for spotting the typos!

Best,
Tobias

**Comment by tmetzke** [comment]
Merged it with 1f89a58e085840f2a68b58a91824c525b5bfa290.
You can always retrieve the changes by visiting the patch of the PR, e.g. https://github.com/camunda/camunda-docs-manual/pull/274.patch in this case.

Thanks for the contribution again.

Best,
Tobias

**Pull request closed without merging**
