### PR TITLE
chore(docs): refactor plugins page

### PR DESCRIPTION
**Pull request by marstamm**
* consistent spacing between content and next headings (Markdown only)
* remove duplicated label explanation in Process Definition Runtime Tab
* Display additional arguments in a list

related to CAM-12591

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
This is how you earn a shirt 😉 🤣 👍

**Comment by marstamm** [comment]
For a t-shirt, I would have created separate PRs for the 3 improvements :rofl:

**Comment by tmetzke** [comment]
Yeah but I would have labelled it `invalid` then 😛

**Comment by marstamm** [comment]
Dang it! More backport branches then :innocent:

**Pull request merged**
