### PR TITLE
chore(docs): fix broken webapps links

### PR DESCRIPTION
**Pull request by danielkelemen**
related to camunda/camunda-bpm-platform#3393

### CODE REVIEW

**Comment by psavidis** [comment]
I've tested the new link and it works. LGTM 👍

**Review by psavidis — APPROVED** [review]

**Comment by psavidis** [comment]
❓ Does this change need to be backports to other versions e.g **7.19**, **7.18**, **7.17**?

**Comment by danielkelemen** [comment]
> ❓ Does this change need to be backported to other versions e.g **7.19**, **7.18**, **7.17**?

It could be in 7.19 but I wouldn't bother. These are just super minor things and they have been there for a while now.

**Review by psavidis — APPROVED** [review]
If the effort is low, personally i think it makes sense to backport the change of the docs to the previous supported versions. It's documentation pointing nowhere. Feel free to proceed as you like with this decision.

**Pull request merged**
