### PR TITLE
chore(introduction): replace AdoptOpenJDK with Eclipse Temurin JDK

### PR DESCRIPTION
**Pull request by psavidis**
related to https://github.com/camunda/camunda-bpm-platform/issues/2947

### CODE REVIEW

**Review by tmetzke — APPROVED** [review]
👍 Good job
🙃 Regarding commit message, maybe focus on the core message, e.g. `chore(introduction): replace AdoptOpenJDK with Eclipse Temurin JDK`

**Comment by psavidis** [comment]
Done

**Comment by tmetzke** [comment]
> Rebased commit messaged to the recommended one above

👍 Looks good
🙃 Try to use the whole issue URL if the issue sits in a different repository. That way, GitHub can link it correctly. Otherwise, it will try to link it locally to this repository which is wrong. In fact, it will link to a different PR in this repository here with the number 2947 at some point in the future when that PR exists.

**Comment by psavidis** [comment]
Updated the commit message to include the exact issue URL.

**Review by tmetzke — APPROVED** [review]
👍 Changes and commit message look good

**Pull request merged**
