### PR TITLE
CAM-10757 - update desc for batchOperationsForHistoryCleanup

### PR DESCRIPTION
**Pull request by garima-camunda**
CAM-10757 - update description for batchOperationsForHistoryCleanup

### CODE REVIEW

**Comment by garima-camunda** [comment]
Committed the suggested changes. Please review.

**Comment by yanavasileva** [comment]
Merged with (e60ffad)

**Comment by garima-camunda** [comment]
Included the process engine plugin in the description of  batchOperationsForHistoryCleanup

**Comment by garima-camunda** [comment]
some minor changes regarding formation of sentence

**Comment by yanavasileva** [comment]
merged with (9086c05)

**Pull request closed without merging**
