### PR TITLE
CAM-11829: Grammatical mistake

### PR DESCRIPTION
**Pull request by tiruis**
"is" is replaced by "are"

### CODE REVIEW

**Comment by tiruis** [comment]
Please tell me whether my defect is valid or invalid

**Comment by yanavasileva** [comment]
The reported grammar error has been merged to the master with the (0017de0) commit.

**Comment by tiruis** [comment]
My change is not merged

**Comment by yanavasileva** [comment]
Hi @tiruis,

I checked the contribution again and added clarification that the page contains two lists instead of one.
Merged with (59e3ef0), thank you for your contribution.

Best regards,
Yana

**Pull request closed without merging**
