### PR TITLE
Keystroke  and table

### PR DESCRIPTION
**Pull request by tiruis**
It will look good if we form a table with action against the key stroke for Keyboard Shortcuts.

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hi @tiruis,

Is this meant to be as a pull request (I see only a whitespace in the commit) or you want to report a ticket for this?
If it's the latter, please consider reporting the ticket via our tracking system - [Jira](https://jira.camunda.com/secure/CreateIssue!default.jspa)


Best,
Yana

**Comment by tiruis** [comment]
I am telling that instead of having the below paragraph we can have it in tabular form.It is suggestion only


Claim the currently selected task: CTRL + ALT + C
Set the keyboard focus to the first filter in the filter list: CTRL + SHIFT + F
Set the keyboard focus to the first task in the list of tasks: CTRL + ALT + L
Set the keyboard focus to the first input field in an embedded task form: CTRL + ALT + F
Open the start process modal dialog: CTRL + ALT + P

**Comment by yanavasileva** [comment]
Hi @tiruis,

Thank you for reporting this.
I created CAM-11891 to tackle it.
Hereby I am closing the PR.

Best regards,
Yana

**Comment by tiruis** [comment]
Duplicate of https://github.com/camunda/camunda-docs-manual/pull/576. So this pull request and JIRA https://jira.camunda.com/browse/CAM-11891 can be closed

**Pull request closed without merging**
