### PR TITLE
fix(introduction): fix license book links

### PR DESCRIPTION
**Pull request by ThorbenLindhauer**
related to camunda/camunda-bpm-platform#3296

### CODE REVIEW

**Comment by tmetzke** [comment]
🙃 Now that you brought this to my attention, I can see some other weird links we might want to correct, like `git:`, `git+ssh:`, and `git+https:`.

**Review by tmetzke — APPROVED** [review]
This should be the only required ones 👍 
I added a comment above for optional other links to adjust.

**Comment by ThorbenLindhauer** [comment]
I'd like to only do the minimal thing to make the build succeed (e.g. any manual fix will be overridden with the next minor release again). If we wanted to improve the other links, we should rather look at how we generate the Markdown. But I don't think that's worth our time at the moment.

**Comment by tmetzke** [comment]
> I'd like to only do the minimal thing to make the build succeed (e.g. any manual fix will be overridden with the next minor release again). If we wanted to improve the other links, we should rather look at how we generate the Markdown. But I don't think that's worth our time at the moment.

Makes sense 👍

**Pull request merged**
