### PR TITLE
docs(history-cleanup): add note for timer-start-event logs

### PR DESCRIPTION
**Pull request by garima-camunda**
related to CAM-11895

### CODE REVIEW

**Comment by yanavasileva** [comment]
@garima-camunda, the pull request is quite old now. Do you still want to apply the requested changes or we can close it?

**Comment by garima-camunda** [comment]
@yanavasileva As this PR is still valid, it would be nice if we can consider applying the changes in the doc.

**Comment by yanavasileva** [comment]
@garima-camunda is it related to CAM or SUPPORT ticket? Is it sufficient to apply the change on master branch (develop version, it'll be part of 7.18 then)?

**Comment by yanavasileva** [comment]
@garima-camunda is it sufficient if the change is applied only on master branch? Then it will be part of 7.18 version.

**Comment by tasso94** [comment]
Hey @garima-camunda,

If you want your PRs picked up by our community-worker process for being reviewed and eventually merged, please unassign yourself as soon as your contribution is ready. Like this, the community worker gets notified to work on it.

Best,
Tassilo

**Comment by garima-camunda** [comment]
@yanavasileva Yes, it would be sufficient to apply changes on the master branch for now.  Thanks.

**Comment by garima-camunda** [comment]
Thanks @tasso94 for letting me know. I have unassigned myself to this PR now. Also, as far as I understand we do not assign ourselves to the PR. But from the history of conversation, it looks like you assigned

**Comment by yanavasileva** [comment]
Merged with 38f698a.

**Pull request closed without merging**
