### PR TITLE
chore(repo): rename Camunda BPM Platform to Camunda Platform

### PR DESCRIPTION
**Pull request by mboskamp**
Related to CAM-12950

### CODE REVIEW

**Review by marstamm — CHANGES_REQUESTED** [review]
I found some places that use "Camunda BPM Runtime". I think we should align this as "Camunda Platform" as well.
In some cases, "Camunda BPM Runtime" appears in a Log or sample payload. Should we update those as well? 

EDIT: I could also be wrong and we don't change the Product name in those cases. If that is the case, feel free to merge :)

https://github.com/camunda/camunda-docs-manual/blob/e4ffcc7111f361ad0a89752560445c1bf1924088/content/reference/deployment-descriptors/tags/process-engine.md#L837
https://github.com/camunda/camunda-docs-manual/blob/131e7dc91dd885f311c9ec3891f1e8fe299766e1/content/webapps/cockpit/extend/plugins.md#L15
https://github.com/camunda/camunda-docs-manual/blob/e4ffcc7111f361ad0a89752560445c1bf1924088/content/user-guide/security.md#L108
https://github.com/camunda/camunda-docs-manual/blob/e4ffcc7111f361ad0a89752560445c1bf1924088/content/introduction/telemetry.md#L54
https://github.com/camunda/camunda-docs-manual/blob/2671a04b04bc75ae17da94e686d74c2115ebb09f/content/user-guide/logging.md#L397
https://github.com/camunda/camunda-docs-manual/blob/e4ffcc7111f361ad0a89752560445c1bf1924088/content/update/minor/713-to-714/_index.md#L36
https://github.com/camunda/camunda-docs-manual/blob/e4ffcc7111f361ad0a89752560445c1bf1924088/content/update/patch-level.md#L578

**Comment by mboskamp** [comment]
@marstamm, thanks for the feedback. Nice catches!
I did not change the telemetry related lines you mentioned above since we need to keep the old name in the telemetry payload (and logging output). All the other files you mentioned are updated now.

**Comment by mboskamp** [comment]
I will open separate PRs for backporting.

**Comment by marstamm** [comment]
On some of the mentioned sites there are more than 1 occurrences. Sorry, I did not make that clear in my first comment. I found further mentions in
1x http://localhost:1313/user-guide/security/ (https://github.com/camunda/camunda-docs-manual/blob/32d15e5260ab167c54a4cea908b41706a2a9f58a/content/user-guide/security.md#L296)
3x http://localhost:1313/user-guide/camunda-bpm-rpa-bridge/

I think we should still rename the Product name in the Telemetry Legal note on https://github.com/camunda/camunda-docs-manual/blob/32d15e5260ab167c54a4cea908b41706a2a9f58a/content/introduction/telemetry.md#L184, even when we don't adjust the rest of the telemetry documentation.

**Review by marstamm — APPROVED** [review]
:rocket:

**Comment by mboskamp** [comment]
I needed to manually rebase onto master, since there were some conflicts. Will merge now.

**Pull request merged**
