### PR TITLE
docs(webapps): document SameSite for session cookie

### PR DESCRIPTION
**Pull request by tmetzke**
related to CAM-14111

### CODE REVIEW

**Review by tasso94 — CHANGES_REQUESTED** [review]
* For Spring Boot, the configuration options are [described in very detail](https://github.com/camunda/camunda-docs-manual/pull/1104/files#diff-07521c2a088a6219fe7041a67e1d938ff1cf3bb905ac7eec6b10db5ada2ac597). 
  * However, I cannot find such a detailed table for Tomcat. On Tomcat, the example only shows how to configure the `sameSiteCookieValue` property. 
For the CSRF prevention cookie, you can find this table here: https://github.com/camunda/camunda-docs-manual/blob/master/content/webapps/shared-options/csrf-prevention.md 
* I would argue against putting it under `webapps/shared-options` since only Tomcat supports it. 
  * What about adding such a table to `installation/full/tomcat`?

**Comment by tmetzke** [comment]
> * For Spring Boot, the configuration options are [described in very detail](https://github.com/camunda/camunda-docs-manual/pull/1104/files#diff-07521c2a088a6219fe7041a67e1d938ff1cf3bb905ac7eec6b10db5ada2ac597).
>   
>   * However, I cannot find such a detailed table for Tomcat. On Tomcat, the example only shows how to configure the `sameSiteCookieValue` property.
>     For the CSRF prevention cookie, you can find this table here: https://github.com/camunda/camunda-docs-manual/blob/master/content/webapps/shared-options/csrf-prevention.md
> * I would argue against putting it under `webapps/shared-options` since only Tomcat supports it.
>   
>   * What about adding such a table to `installation/full/tomcat`?

I like that idea very much! I was actually wondering myself why we only have the details for CSRF in Spring Boot and completely overlooked the detailed description in the `webapps/shared-options/csrf-prevention` 👍

**Review by tasso94 — APPROVED** [review]
🚀

**Comment by tmetzke** [comment]
@christinaausley, can you please do a technical writing review? 🙂

**Comment by christinaausley** [comment]
This looks good from a technical writing perspective. Ensure you add me as a reviewer prior to merge for the next PR so I can make changes if necessary.

**Comment by tmetzke** [comment]
Thanks, @christinaausley!
Regarding the merge: we decided to do the merge already since we were short on time and needed to get a patch release ready.

Process-wise, I think you can still add suggestions after the merge to this PR.
It will then be my problem to transfer that into a new PR, which I am aware of if I merge it before you've reviewed that.

**Comment by christinaausley** [comment]
@tmetzke Excellent! I figured since I was out on holiday last week you would need to given the timing. No worries at all.

Thanks for clarifying. Regardless, no changes on my end, so no need to go back and make adjustments for this one!

**Pull request merged**
