### PR TITLE
CAM-11394: Updates on skipped versions

### PR DESCRIPTION
**Pull request by superbeagle**
[CAM-11394](https://app.camunda.com/jira/browse/CAM-11394)

Added clarifications on how to 'skip' minor versions by indicating database alteration scripts from every minor version need to be executed. In a rolling update, every node has to be updated before the update to the next minor version can be executed.

### CODE REVIEW

**Comment by yanavasileva** [comment]
Hi Joe,

Thank you for your contribution.
We will have a look to merge the proposal.
(Sorry for the referenced commit, I messed up the commit message there.)

Best regards,
Yana

**Comment by ThorbenLindhauer** [comment]
Hey Joe,

Thanks for contribution. I think it is generally a good idea to make people aware that they do not have to update the Camunda libraries to every in-between version. However, we also see the risk that people may misunderstand the "Skipping Minor Versions" hint such that they will skip the migration guide for some versions entirely (except the DB part). We should try to make it more clear that the skipping only applies to the library update. If that is not so easy, I would rather not have this hint, as the current state causes confusion but no harm, whereas people skipping important parts of the migration guide can cause severe issues in their systems.

What do you think?

Cheers,
Thorben

**Comment by superbeagle** [comment]
Hi Thorben,
     I certainly understand the challenges with potential confusion. I kept seeing this question being asked in different channels which was my original motivation for the update. I put the update in a warning box in the hopes of highlighting it. Maybe make it part of each update?

Joe

**Comment by superbeagle** [comment]
or maybe a rewording of 'skip'

**Comment by superbeagle** [comment]
Something like this?
{{< note title="Do I need to apply every minor version if I missed a few?" class="warning" >}}
If you need to apply multiple minor versions you MUST execute the database alteration scripts in minor version order as they are NOT cumulative. Application library updates are cumulative and don't require sequential minor version updates. You can simply apply your target minor version application libraries.
{{< /note >}}

**Comment by ThorbenLindhauer** [comment]
I like the version in your last comment. Maybe we can add an extra sentence that the migration guide for every minor version should be checked.

**Comment by superbeagle** [comment]
Will do....so once we come up with something should I publish again on this branch and create another pull request? Or use this one?

**Comment by ThorbenLindhauer** [comment]
You can just add another commit to this branch. I will squash them on the merge.

**Comment by superbeagle** [comment]
Will do and will add another commit later today

**Comment by ThorbenLindhauer** [comment]
I merged your contribution via https://github.com/camunda/camunda-docs-manual/commit/590e46866f349e0fc895383d782fe712814c1edd. I changed the explanation why the migration guide should be consulted slightly, and I made the commit message comply to our commit message style. Thanks for your work!

**Pull request closed without merging**
