### PR TITLE
Security Policy Improvements

### PR DESCRIPTION
**Pull request by gimbel**
Sorry for so many commits with the same message. I am unable to follow the commit guidelines and squash it into one commit.

### CODE REVIEW

**Comment by romansmirnov** [comment]
Hi @yanavasileva,

Could you please merge the pull request? Before merging it, could you please squash all the commits?

Best,
Roman

**Comment by yanavasileva** [comment]
Hi,

Are those changes only for current version?

Best regards,
Yana

**Comment by meyerdan** [comment]
Hi Yana, it should be merged to all versions which have this page. Thanks!

**Comment by yanavasileva** [comment]
Hi Robert,

I merged the pull request in 7.9, 7.8, 7.7.

Best regards,
Yana

**Pull request closed without merging**
